var DISQUS=function(h){var e={AssertionError:function(a){this.message=a}};e.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};e.assert=function(a,c){if(!a)throw new e.AssertionError(c);};var d=[];e.define=function(a,c){typeof a==="function"&&(c=a,a="");for(var b=a.split("."),g=b.shift(),f=e,o=(c||function(){return{}}).call({overwrites:function(b){b.__overwrites__=!0;return b}},h);g;)f=f[g]?f[g]:f[g]={},g=b.shift();for(var k in o)o.hasOwnProperty(k)&&
(o.__overwrites__||f[k]!==null&&e.assert(!f.hasOwnProperty(k),"Unsafe attempt to redefine existing module with "+k),f[k]=o[k],d.push(function(b,g){return function(){delete b[g]}}(f,k)));return f};e.use=function(a){return e.define(a)};e.cleanup=function(){for(var a=0;a<d.length;a++)d[a]()};return e}(this);
DISQUS.define(function(h,e){var d=h.document,a=d.getElementsByTagName("head")[0]||d.body,c={running:!1,timer:null,queue:[]};DISQUS.defer=function(b,g){function a(){var b=c.queue;if(b.length===0)c.running=!1,clearInterval(c.timer);for(var g=0,f;f=b[g];g++)f[0]()&&(b.splice(g--,1),f[1]())}c.queue.push([b,g]);a();if(!c.running)c.running=!0,c.timer=setInterval(a,100)};DISQUS.each=function(b,g){var a=b.length,c=Array.prototype.forEach;if(isNaN(a))for(var d in b)b.hasOwnProperty(d)&&g(b[d],d,b);else if(c)c.call(b,
g);else for(c=0;c<a;c++)g(b[c],c,b)};DISQUS.extend=function(b){DISQUS.each(Array.prototype.slice.call(arguments,1),function(g){for(var a in g)b[a]=g[a]});return b};DISQUS.serializeArgs=function(b){var a=[];DISQUS.each(b,function(b,c){b!==e&&a.push(c+(b!==null?"="+encodeURIComponent(b):""))});return a.join("&")};DISQUS.isString=function(b){return Object.prototype.toString.call(b)==="[object String]"};DISQUS.serialize=function(b,a,c){a&&(b+=~b.indexOf("?")?b.charAt(b.length-1)=="&"?"":"&":"?",b+=DISQUS.serializeArgs(a));
if(c)return a={},a[(new Date).getTime()]=null,DISQUS.serialize(b,a);a=b.length;return b.charAt(a-1)=="&"?b.slice(0,a-1):b};DISQUS.require=function(b,c,f,e,h){function m(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))e&&e(),l&&clearTimeout(l),DISQUS.bean.remove(a.target,p,m)}var i=d.createElement("script"),p=i.addEventListener?"load":"readystatechange",l=null;i.src=DISQUS.serialize(b,c,f);i.async=!0;i.charset="UTF-8";(e||h)&&DISQUS.bean.add(i,p,m);h&&(l=setTimeout(function(){h()},
2E4));a.appendChild(i);return DISQUS};DISQUS.requireStylesheet=function(b,c,f){var e=d.createElement("link");e.rel="stylesheet";e.type="text/css";e.href=DISQUS.serialize(b,c,f);a.appendChild(e);return DISQUS};DISQUS.requireSet=function(a,c,f){var e=a.length;DISQUS.each(a,function(a){DISQUS.require(a,{},c,function(){--e===0&&f()})})};DISQUS.injectCss=function(b){var c=d.createElement("style");c.setAttribute("type","text/css");b=b.replace(/\}/g,"}\n");h.location.href.match(/^https/)&&(b=b.replace(/http:\/\//g,
"https://"));c.styleSheet?c.styleSheet.cssText=b:c.appendChild(d.createTextNode(b));a.appendChild(c)}});
DISQUS.define("JSON",function(){function h(a){return a<10?"0"+a:a}function e(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(a){var b=k[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(a,b){var g,h,i,k,l=f,n,j=b[a];j&&typeof j==="object"&&typeof j.toJSON==="function"&&!c&&(j=j.toJSON(a));typeof m==="function"&&(j=m.call(b,a,j));switch(typeof j){case "string":return e(j);case "number":return isFinite(j)?String(j):"null";case "boolean":case "null":return String(j);
case "object":if(!j)return"null";f+=o;n=[];if(Object.prototype.toString.apply(j)==="[object Array]"){k=j.length;for(g=0;g<k;g+=1)n[g]=d(g,j)||"null";i=n.length===0?"[]":f?"[\n"+f+n.join(",\n"+f)+"\n"+l+"]":"["+n.join(",")+"]";f=l;return i}if(m&&typeof m==="object"){k=m.length;for(g=0;g<k;g+=1)h=m[g],typeof h==="string"&&(i=d(h,j))&&n.push(e(h)+(f?": ":":")+i)}else for(h in j)Object.hasOwnProperty.call(j,h)&&(i=d(h,j))&&n.push(e(h)+(f?": ":":")+i);i=n.length===0?"{}":f?"{\n"+f+n.join(",\n"+f)+"\n"+
l+"}":"{"+n.join(",")+"}";f=l;return i}}var a={},c=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+h(this.getUTCMonth()+1)+"-"+h(this.getUTCDate())+"T"+h(this.getUTCHours())+":"+h(this.getUTCMinutes())+":"+h(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,o,k={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},m;a.stringify=function(a,b,c){var g;o=f="";if(typeof c==="number")for(g=0;g<c;g+=1)o+=" ";else typeof c==="string"&&(o=c);if((m=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return d("",{"":a})};a.parse=function(a,c){function g(a,
b){var f,e,d=a[b];if(d&&typeof d==="object")for(f in d)Object.hasOwnProperty.call(d,f)&&(e=g(d,f),e!==void 0?d[f]=e:delete d[f]);return c.call(a,b,d)}var f,a=String(a);b.lastIndex=0;b.test(a)&&(a=a.replace(b,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+a+")"),
typeof c==="function"?g({"":f},""):f;throw new SyntaxError("JSON.parse");};var i={a:[1,2,3]},p,l;if(Object.toJSON&&Object.toJSON(i).replace(/\s/g,"")==='{"a":[1,2,3]}')p=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(i='{"a":[1,2,3]}'.evalJSON(),i.a&&i.a.length===3&&i.a[2]===3&&(l=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),c=!(a&&a.length===3&&a[2]===3))})();if(c||!p||!l)return{stringify:a.stringify,parse:a.parse};return{stringify:p,
parse:l}});
DISQUS.define("Bus",function(){function h(a){a=a.split("/");return a[0]+"//"+a[2]}var e=DISQUS.use("JSON"),d=window.location.hash.slice(1),a=window.parent,c=document.referrer,b={};b.client=h(document.location.href);b.host=c?h(c):b.client;return{origins:b,postMessage:function(c){c.sender=d;c=e.stringify(c);a.postMessage(c,b.host)},sendHostMessage:function(a,b){b=b||[];DISQUS.Bus.postMessage({scope:"host",name:a,data:b})},sendGlobalMessage:function(a,b){b=b||[];DISQUS.Bus.postMessage({scope:"global",name:a,
data:b})}}});_.extend(DISQUS.Bus,Backbone.Events);$(document).ready(function(){var h=window.addEventListener?window.addEventListener:window.attachEvent,e=window.addEventListener?"message":"onmessage";if(!h)throw Error("No event support.");h(e,function(d){var a=DISQUS.Bus,c=d.origin;if(!(c!=a.origins.client&&c!=a.origins.host)){var b;try{b=DISQUS.JSON.parse(d.data)}catch(g){return}d=b.data;switch(b.scope){case "client":a.trigger(d.eventName,d.data)}}},!1)});
DISQUS.define(function(h,e){var d={blocks:{},ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",bean:require("bean"),debug:!1,browser:{mobile:navigator.userAgent.match(/Android|webOS|iPhone|iPad|iPod|BlackBerry/i)},modules:{},strings:{translations:{}}};d.strings.get=_.bind(function(a){var b=this.translations[a];return b!==e?b:a},d.strings);d.interpolate=function(a,b){return a.replace(/%\(\w+\)s/g,function(d){var d=d.slice(2,-2),f="";d in b?f=
b[d]!==e?b[d].toString():"":DISQUS.logError&&DISQUS.logError("Key `"+d+"` not found in context for: ",a);return f})};d.addBlocks=function(){return function(a){a(DISQUS)}};d.templateGlobals={urls:DISQUS.use("urls"),sso:null,trans:d.strings.get,_:{pluralize:_.pluralize}};d.renderBlock=function(a,b){return DISQUS.blocks[a](d.templateGlobals,b)};d.assureOffset=function(a){return a.indexOf("+")>=0?a:a+"+00:00"};var a=d.Builder=function(){this.accum=[]};_.extend(a.prototype,{put:function(a){this.accum.push(a)},
esc:function(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")},compile:function(){return this.accum.join("")}});return d});
DISQUS.define("urls",function(){var h=encodeURIComponent(document.referrer),e={root:"http://disqus.com",media:"http://mediacdn.disqus.com/1348862029",loading:"http://mediacdn.disqus.com/1348862029/html/simple-loading.html",realertime:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+h,editProfile:"http://disqus.com/account/",verifyEmail:"https://disqus.com/next/verify/",authorize:"https://disqus.com/api/oauth/2.0/authorize/",
moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"http://mediacdn.disqus.com/1348862029/images/noavatar92.png"}};window.location.protocol==="https:"&&(e=_.extend(e,{root:"",media:"",loading:"/html/simple-loading.html",realertime:e.realertime.replace("http://","https://"),api:e.apiSecure,logout:"https://disqus.com/logout/?redirect="+h,editProfile:"https://disqus.com/account/",
moderate:"https://disqus.com/admin/moderate/",oauth:{twitter:"https://disqus.com/_ax/twitter/begin/",google:"https://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"/images/noavatar92.png"}}));return e});
DISQUS.define("api",function(){function h(a){function c(d){var e=d.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,e.length)===e&&(d=DISQUS.JSON.parse(d.originalEvent.data),d.requestId==b&&(e=d.code===0?a.success:a.error,delete d.requestId,(e||function(){})(d),document.body.removeChild(h),document.body.removeChild(f),$(window).unbind("message",c)))}var b=_.uniqueId(),d=document.createElement("div"),f=document.createElement("form"),e="frame_"+b,h;d.innerHTML='<iframe name="'+e+'"></iframe>';h=d.childNodes[0];
f.target=e;f.action=a.url.replace(".json",".pm");f.method=a.method||"GET";a.data=_.extend(a.data,{callback:b,referrer:document.referrer});_.each(a.data,function(a,b){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var c=document.createElement("input");c.type="hidden";c.name=b;c.value=a;f.appendChild(c)})});$(window).bind("message",c);document.body.appendChild(h);document.body.appendChild(f);f.submit()}function e(a){a=_.defaults(a,d);a.data=a.data||{};a.data.api_key=
DISQUS.apiKey;$.ajax(a)}var d={};return{defaults:function(a){_.extend(d,a)},getURL:function(a,c){c=c||{};if(c.secure||window.location.protocol==="https:")return DISQUS.urls.apiSecure+a;return DISQUS.urls.api+a},ajax:e,call:function(a,c){c=c||{};c.url=DISQUS.api.getURL(a,{secure:c.secure});c.data=_.extend(c.data||{},{api_key:DISQUS.apiKey});(c.secure?h:e)(c)}}});
(function(h){var e=DISQUS.Bus,d=DISQUS.api.getURL("internal/switches/list.jsonp");h.switches_jsonp_cb=function(a){e.sendHostMessage("switches.received",a.response)};e.on("fetch",function(a){a=a||{};a.data=a.data||{};a.data.callback="switches_jsonp_cb";a.data.api_key=DISQUS.apiKey;a=DISQUS.serialize(d,a.data,!1);DISQUS.require(a)});e.sendHostMessage("ready")})(this);